apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: frontend
build:
  artifacts:
    - image: frontend-react-app
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - kubernetes/frontend-react-app-deployment.yaml
    - kubernetes/frontend-react-app-service.yaml
portForward:
  - resourceType: deployment
    resourceName: frontend-react-app
    port: 80
    localPort: 80
