apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\kompose\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend-react-app
  name: frontend-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend-react-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\kompose\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: frontend-react-app
    spec:
      containers:
        - image: frontend-react-app
          name: frontend-react-app
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
